dist: trusty
language: c++
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
env:
  - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

script:
  - wget -N https://www.nabto.com/downloads/nabto-libs/4.1.1/nabto-libs.zip
  - unzip nabto-libs.zip
  - cp nabto-libs/linux64/lib/libnabto_*.a lib/
  - cp nabto-libs/linux64/include/nabto_client_api.h include/
  - mkdir -p build
  - cd build
  - cmake ..
  - make
