language: c++
matrix:
  include:
    - os: linux
      dist: trusty
      language: c++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: osx
      osx_image: xcode9.1

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - wget -N https://www.nabto.com/downloads/nabto-libs/4.1.1/nabto-libs.zip
  - unzip nabto-libs.zip
  - cp nabto-libs/linux64/include/nabto_client_api.h include/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp nabto-libs/linux64/lib/libnabto_client_api.so lib/; fi;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp nabto-libs/mac64/lib/libnabto_client_api.dylib lib/; fi;
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=`pwd` ..
  - cmake --build . --target install
  - ./bin/nabto-cli -v
