language: c++
matrix:
  include:
  - os: linux
    dist: trusty
    language: c++
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9
    env:
    - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
  - os: osx
    osx_image: xcode9.1
before_install:
- eval "${MATRIX_EVAL}"
script:
- wget -N https://www.nabto.com/downloads/nabto-libs/4.1.1/nabto-libs.zip
- unzip nabto-libs.zip
- cp nabto-libs/linux64/include/nabto_client_api.h include/
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp nabto-libs/linux64/lib/libnabto_client_api.so
  lib/; fi;
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp nabto-libs/mac64/lib/libnabto_client_api.dylib
  lib/; fi;
- mkdir -p build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=install ..
- cmake --build . --target install
- "./install/nabto-cli -v || exit 1"
- cmake --build . --target package
deploy:
  provider: releases
  api_key:
    secure: W4YBtEhgoGJcDIpF8oQMwNubm6Qv85SNbZcTmCGBh/r6S5jETwj9gWIJl8WCWBZsb1+7naPFEgEHTcwnL8mI1iCae6/N7vW1ARZGhaDTJkPRZSEMztNg/S2J2SQ5XEXTjka8HWtRizyEP0mCb1xgJPhT8F2LJDNR16+VqfdhQ6yQ1XKGDR4kQ9NLCr2BKrwMvhw0FUXWYM4Ibz21B8JE8ygA6f6/tr1VRAzH52IcrHBD3q4RSb7xTDA1+HEPsh8fZFvMUsu1IScVTcZTm5I/b7PXaKQFJEOfo//V1nICt1UIJqTEzb5VWIIB5XmHmJsvoKkTpU12wUW27bkR6KWDfYHaKToguPqGBjKuMyywYg0/A7uuYphGV7b0efkaBuuFLnuSqEmNumhYL01tgINxGC7soMQEQKGtWzgYzvVBkioy+kVUu29ZwhefH6bLAMwasb0D3b+NUEzVD2QgP+LhWNDjimqHMgzaw43nASvPqaqEvS8qlirtmeLZ2pp0Yf3lY3fbNHKDR1xP9WdWGi9191392UM6OWIjWWoNLDKqVGxO6BYjMeH+KvMgO7bG2OxNTh6wsCJYg9HCUJ+bexcgax2PixV7aPIuhZ8jcwXUBSGH9430Edlpa6da5BGH+wzXwDEo8ZYXAyOGnMpMpmjQKmqRWd4YZZhJO1esbQ2Bha4=
  file_glob: true
  file: build/nabto-cli-*.zip
  skip_cleanup: true
  on:
    tags: true
