version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    curl https://www.nabto.com/downloads/nabto-libs/4.1.1/nabto-libs.zip -o nabto-libs.zip

    7z x nabto-libs.zip

    cp nabto-libs\win32\lib\*.lib lib\
    cp nabto-libs\win32\include\nabto_client_api.h include\
    
    mkdir build || exit 1
    
    cd build || exit 1
    
    cmake -DCMAKE_BUILD_TYPE=Release --config Release .. || exit 1
    
    cmake --build . --config Release || exit 1