version: 1.0.{build}
image: Visual Studio 2017
build: Script
build_script:
- cmd: >-
    curl https://downloads.nabto.com/assets/nabto-libs/4.4.0/nabto-libs.zip -o nabto-libs.zip

    7z x nabto-libs.zip

    copy nabto-libs\win32-static\bin\*.dll lib\

    copy nabto-libs\win32-static\lib\nabto_client_api.lib lib\

    copy nabto-libs\win32-static\include\nabto_client_api.h include\

    mkdir build || exit 1

    cd build || exit 1

    cmake -DCMAKE_GENERATOR_TOOLSET=v141_xp -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release --config Release .. || exit 1

    cmake --build . --config Release --target INSTALL || exit 1

    install\nabto-cli -v || exit 1

    cmake --build . --config Release --target package || exit 1

artifacts:
- path: build\nabto-cli-windows.zip
  name: nabto-cli-windows
deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: /ZS7w9J1/2S5ise/ZkEA/aig3ASgfNwS6uiPCMHlg4s6AH1+RPF0UY1FcP784Gyv
  artifact: /nabto-cli-windows.zip/
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true
