version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    curl https://www.nabto.com/downloads/nabto-libs/4.1.1/nabto-libs.zip -o nabto-libs.zip

    7z x nabto-libs.zip

    copy nabto-libs\win32-static\bin\nabto_client_api.dll lib\

    copy nabto-libs\win32-static\lib\nabto_client_api.lib lib\

    copy nabto-libs\win32-static\include\nabto_client_api.h include\
    
    mkdir build || exit 1
    
    cd build || exit 1
    
    cmake -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release --config Release .. || exit 1
    
    cmake --build . --config Release --target INSTALL || exit 1

    install\nabto-cli -v || exit 1

    cmake --build . --config Release --target package || exit 1
