name: CMake

on:
  push:

env:
  BUILD_TYPE: Release

jobs:
  build:
    permissions:
      # TODO split job in two, one which builds and tests the software and one which uploads the assets with write permissions.
      # This is just a best practice and not a problem as we do not build untrusted code.
      contents: write
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Fetch libs
      run: curl https://downloads.nabto.com/assets/nabto-libs/4.4.0/nabto-libs.zip -o nabto-libs.zip

    - name: Unpack libs
      run: 7z x nabto-libs.zip

    - name: copy dll
      run: copy nabto-libs\win32-static\bin\*.dll lib\

    - name: copy lib
      run: copy nabto-libs\win32-static\lib\nabto_client_api.lib lib\

    - name: copy header
      run: copy nabto-libs\win32-static\include\nabto_client_api.h include\

    - name: Configure CMake
      run: cmake -DCMAKE_GENERATOR_TOOLSET=v141_xp -A Win32 -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target INSTALL

    - name: Test
      run: .\install\nabto-cli -v

    - name: package
      run:  cmake --build ${{github.workspace}}/build --config Release --target package

    - name: Archive package
      uses: actions/upload-artifact@v3
      with:
        name: nabto-cli-windows
        path: |
          .\build\nabto-cli-windows.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: .\build\nabto-cli-windows.zip
